# Generated by Django 4.2 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_profile_image_remove_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cv_extracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
