# Generated by Django 4.2 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_cv_extracted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_url",
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin_url",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
